apiVersion: v1
kind: Deployment
metadata:
  labels:
    run: ${IMAGE_NAME}
  name: ${IMAGE_NAME}
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      containers:
      - command:
        - bash
        - /init-actions/cloudbuild/presubmit.sh
        env:
        - name: COMMIT_SHA
          value: ${COMMIT_SHA}
        - name: IMAGE_VERSION
          value:${IMAGE_VERSION}
        image: gcr.io/cloud-dataproc-ci/init-actions-image:${BUILD_ID}
        name: ${IMAGE_NAME}
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
        securityContext:
          capabilities:
            drop:
            - NET_RAW
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-9ltw8
          readOnly: true
